name: Build and deploy to Kuroco front (test ref)
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  # for Pull Request (exclude merged)
  pullreq_build:
    name: Build(pullreq)
    if: (github.repository == 'sakaguchi-diverta/kuroco_front_http_status' && github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/kuroco stage') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: "Get branch name and sha"
        id: get_branch
        run: |
          PR=$(curl -H "X-Kuroco-Auth: token a6e1ac02ce54195350ba7bc6242bf2d0" https://stg-marunouchi.g.kuroco.app/direct/menu/github/?pr=${{ github.event.issue.pull_request.url }})
          echo "branch=$(echo $PR | jq -r '.ref')" >> $GITHUB_OUTPUT
          echo "sha=$(echo $PR | jq -r '.sha')" >> $GITHUB_OUTPUT
          echo $PR
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_branch.outputs.branch }}
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'sakaguchi-diverta/kuroco_front_http_status' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v1
        env:
          webhook_url: "https://sakaguchi.g.kuroco.app/direct/menu/github/"
          webhook_secret: "6560f1374199e491072298fabca51c8d"
          data: '{"domain":"sakaguchi.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
